version: '3'
services:
  frontend:
    image: appsc.azurecr.io/nginx-frontend-test:latest
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - my_network

  backend:
    image: appsc.azurecr.io/flask-backend-test:latest
    container_name: flask
    ports:
      - "5000:5000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
