name: Security and Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  TRIVY_VERSION: 0.56.1
  BATS_LIB_PATH: '/usr/lib/'

jobs:
  Security_and_Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Bats and Bats Libraries
        uses: bats-core/bats-action@v1

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v${{ env.TRIVY_VERSION }}
          trivy --version

      - name: Run Trivy Vulnerability Scan
        run: |
          trivy fs --scanners vuln,secret --exit-code 1 --severity CRITICAL,HIGH .
        env:
          TRIVY_CACHE_DIR: .cache
          TRIVY_DISABLE_VEX_NOTICE: true
          TRIVY_DEBUG: true

      - name: Run Bats Tests
        run: |
          bats --recursive --timing --verbose-run .
