name: Security and Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  TRIVY_VERSION: 0.56.1
  BATS_LIB_PATH: '/usr/lib/'

jobs:
  Security_and_Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bats and Bats-libs
        uses: bats-core/bats-action@main
        id: setup-bats
        with:
          bats-version: ${{ matrix.version }}
          support-clean: "false"
          assert-clean: "false"
          detik-clean: "false"
          file-clean: "false"
     # - name: Execute example tests
       # env:
         # TERM: xterm    
       # shell: bash
        #run:
         # bats -T -p tests           
          
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v${{ env.TRIVY_VERSION }}
          trivy --version

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          format: 'fs'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          update-db: false 
          cache-dir: ".trivycache"  
          
      - name: Run Bats Tests
        run: |
          bats --recursive --timing --verbose-run .
