name: Security and Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  TRIVY_VERSION: 0.56.1
  BATS_LIB_PATH: '/usr/lib/'

jobs:
  Security_and_Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bats and Bats-libs
        uses: bats-core/bats-action@main
        id: setup-bats
        with:
          bats-version: ${{ matrix.version }}
          support-clean: "false"
          assert-clean: "false"
          detik-clean: "false"
          file-clean: "false"
     # - name: Execute example tests
       # env:
         # TERM: xterm    
       # shell: bash
        #run:
         # bats -T -p tests           
          
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v${{ env.TRIVY_VERSION }}
          trivy --version
      - name: Cache Trivy DB
        uses: actions/cache@v3
        with:
          path: .cache/trivy
          key: ${{ runner.os }}-trivy-${{ env.TRIVY_VERSION }}          
      - name: Scan Repository for Vulnerabilities
        run: |
          trivy fs --scanners vuln,secret --severity CRITICAL,HIGH . -o trivy-results.json
        env:
          TRIVY_CACHE_DIR: .cache
          TRIVY_DISABLE_VEX_NOTICE: true              
                    
      - name: View Trivy Report
        run: |
          cat trivy-results.json
          
      - name: Run Bats Tests
        run: |
          bats --recursive --timing --verbose-run .
